### PR TITLE
(v2) donot allow email integration if not configured

### PR DESCRIPTION
**Pull request by ibreakthecloud**
- refactor integration to accept `context` in `New()`
- donot allow user to add email in integration if email os not configured

### CODE REVIEW

**Comment by ibreakthecloud** [comment]
todo: refactor: avoid passing `context` in integration methods. Set in the the integration object and use it there to avoid context duplication

**Review by ramanan-ravi — APPROVED** [review]

**Comment by ibreakthecloud** [comment]
> @ibreakthecloud Should we warn user when email configuration is deleted and there is an active email integration?

makes sense.
So, 
- should we restrict user from deleting Email config, and tell them to delete email integrations first if email integration exists or, 
- should we show generic message while deleting saying "All you email integration will be deleted", irrespective of email integration exists and if they continue we delete email integrations too?

**Comment by ramanan-ravi** [comment]
I think we should just show a warning message. (May be a double confirmation popup like "do you still want to proceed?")

We should not delete integrations. There was time involved in configuring them. Asking to reconfigure is not good experience.

A genuine case is SES keys changed. I delete and create. Or I move from SMTP to SES.

**Comment by shyam-dev** [comment]
Valid point. So.

While deleting an email configuration, if email integrations are configured, we just show a message that email integrations will not work anymore.

**Comment by ibreakthecloud** [comment]
> Valid point. So.
> 
> While deleting an email configuration, if email integrations are configured, we just show a message that email integrations will not work anymore.

This becomes a separate ticket, since the changes are only in frontend, will create.

**Comment by ibreakthecloud** [comment]
Merging this for now on the @ramanan-ravi approval
thanks

**Pull request merged**
