### PR TITLE
Fixed empty option value in the table column options

### PR DESCRIPTION
**Pull request by saiprasanth1303**
Fixes # .

Changes proposed in this pull request:
- Fixed empty option value in the table column options

@deepfence/engineering

### CODE REVIEW

**Review by manV — CHANGES_REQUESTED** [review]
I think instead of changing the dropdown component itself, we should fix the table in question. Currently we are setting empty header for the column we want to hide instead of removing it from the columns array altogether, we should change this and remove the column from columns array if we don't want to show this.

**Comment by saiprasanth1303** [comment]
@manV We can't remove that column because we still need to show it for cloud scan results. There is no data for it in host or cluster scans so we just hide it by not showing the column name.

**Comment by manV** [comment]
@saiprasanth1303 why can't we remove column conditionally?

**Comment by manV** [comment]
Stale, Closing.

**Pull request closed without merging**
