### PR TITLE
Deprecate ioutil

### PR DESCRIPTION
**Pull request by Juneezee**
Changes proposed in this pull request:
- Formats the code by running `go fmt ./...` and `go mod tidy`.
- The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

@deepfence/engineering

### CODE REVIEW

**Comment by ramanan-ravi** [comment]
@Juneezee Thanks for your contribution

**Comment by ramanan-ravi** [comment]
@Juneezee I reverted the pr since it is breaking the build. The weaveworks/scope code in this repo is a bit older version, uses golang 1.13.
We will first merge latest https://github.com/weaveworks/scope/releases to this repo.

**Comment by shyam-dev** [comment]
Hello @Juneezee - We are going to wait on this PR for a bit. We are upgrading some of the other dependencies. Once that is done, we will go ahead and merge it.

**Comment by jatin-baweja** [comment]
Hi @Juneezee 

Thanks for your contribution. We have now upgraded scope and have raised a PR with `ioutil` changes, with changes in some additional places.

**Pull request merged**
